### ISSUE TITLE
Data Validation Enhancement To-Do List

### ISSUE THREAD

**Issue by Dr-Scott-James** [Dr-Scott-James/pykalk#3]
In order to get rid of the data validation issue noted in #2 , we should:

- [x] Get input
- [ ] Try to convert input to numeric
- [ ] On failure, give user option to re-enter (going back to top of list) or quit
- [ ]  On quit, cleanly exit the program with a notice as to why the program was closed.
